server:
  port: 8888
spring:
  application:
    name: reggie_take_out  #设置这个项目的名字（默认是项目文件的名字）
  datasource:
    url: jdbc:mysql://localhost:13306/reggie?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    redis:
      time-to-live: 180000  #2s
  redis:
    host: 192.168.15.129
    port: 6379
    password:
    database: 1
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100
        min-idle: 4
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: E:\reggie_upload_photos\